export const env = {
  PORT: Number(process.env.PORT || 4100),
  DATABASE_URL: process.env.DATABASE_URL || "postgresql://family_edu:family_edu@localhost:5432/family_edu",
  JWT_SECRET: process.env.JWT_SECRET || "dev-only-change-me",
  INVITE_CODES: new Set((process.env.INVITE_CODES || "HE-2026,JOJO-2026").split(",").map((item) => item.trim()).filter(Boolean)),
  PUBLIC_PATH: process.env.PUBLIC_PATH || "",
  WEB_DIST: process.env.WEB_DIST || "public",
  MCP_TOKEN: process.env.MCP_TOKEN || "",
  MCP_FAMILY_ID: process.env.MCP_FAMILY_ID || "family_001",
  WECHAT_APP_ID: process.env.WECHAT_APP_ID || "",
  WECHAT_APP_SECRET: process.env.WECHAT_APP_SECRET || "",
  S3_ENDPOINT: process.env.S3_ENDPOINT || "",
  S3_PORT: Number(process.env.S3_PORT || 0),
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY || "",
  S3_SECRET_KEY: process.env.S3_SECRET_KEY || "",
  S3_BUCKET: process.env.S3_BUCKET || "family-edu-files",
  S3_USE_SSL: process.env.S3_USE_SSL === "true",
  STORAGE_DIR: process.env.STORAGE_DIR || "/app/storage",
};
